### PR TITLE
add postForm with multi data content type support

### PR DESCRIPTION
**Pull request by Cyberhan123**

### CODE REVIEW

**Comment by Cyberhan123** [comment]
https://github.com/gogf/gf/issues/843

**Comment by gqcn** [comment]
@Cyberhan123 Please fix these:
1. The CI failed.
2. Please add unit testing case for your updates.

**Review by gqcn — CHANGES_REQUESTED** [review]
@Cyberhan123 Please fix these:
1. The CI failed.
2. Please add unit testing case for your updates.

**Comment by Cyberhan123** [comment]
> @Cyberhan123 Please fix these:
> 
> 1. The CI failed.
> 2. Please add unit testing case for your updates.

Both unit tests and CI are done and fixed.

**Review by gqcn — APPROVED** [review]

**Pull request merged**
