### PR TITLE
feat(ghttp): add middleware `MiddlewareGzip` for compressing response content using gzip

### PR DESCRIPTION
**Pull request by dwSun**
Add a new middleware MiddlewareGzip to handle gzip compression of content, which can effectively reduce the length of the returned data and reduce traffic pressure.

### CODE REVIEW

**Comment by gqcn** [comment]
@dwSun Hello, the goling ci failed, please update your codes. Besides, please commit associated unit testing case to cover your codes.

**Comment by gqcn** [comment]
@dwSun Hello, the CI failed, please have a check.

**Comment by dwSun** [comment]
The same code works just fine inside my own project, but when I put it in gf's repository, I have problems testing it.I don't know why yet.

**Comment by gqcn** [comment]
@dwSun Sorry, I could not figure out the issue reason either, so I post an implements for `MiddlewareGzip` here https://github.com/gogf/gf/pull/4008

**Pull request closed without merging**
