### PR TITLE
Support immutable collections.

### PR DESCRIPTION
**Pull request by syhily**
Add the immutable ability for `garray`, `gmap`, `gset`.

### CODE REVIEW

**Comment by gqcn** [comment]
@syhily I think it'd better using interface instead of defining new struct implementing immutable feature.

**Comment by syhily** [comment]
Using immutable interface means that they share same struct, but this don't make the instance immutable. Case we can force cast the immutable instance to its real struct. Wrapping the mutable instance to a immutable would be better on this scenario.

**Comment by gqcn** [comment]
> Using immutable interface means that they share the same struct, but this don't make the instance immutable. Case we can force cast the immutable instance to its real struct. Wrapping the mutable instance into an immutable struct would be better on this scenario.

There're so many repeated codes between the containers and their immutable feature version. Using interface design implementing immutable feature makes few and easy-maintaining codes for the containers. The immutable  interface can export some read-only method in its definition to make its container immutable. I think you may create a new container struct using `Clone` function and return it as an immutable interface to reduce the repeated and unnecessary codes.

**Comment by syhily** [comment]
> > Using immutable interface means that they share the same struct, but this don't make the instance immutable. Case we can force cast the immutable instance to its real struct. Wrapping the mutable instance into an immutable struct would be better on this scenario.
> 
> There're so many repeated codes between the containers and their immutable feature versions. Using interface design implementing immutable feature makes few and easy-maintaining codes for the containers. The immutable interface can export some read-only method in its definition to make its container immutable. I think you may create a new container struct using `Clone` function and return it as an immutable interface to reduce the repeated and unnecessary codes.

This could be the best solution. I will push the new code today.

**Comment by gqcn** [comment]
@syhily After thinking of it many times, I feel that the implementation of this feature is not graceful, so I decided not to merge this feature into the main branch.

**Pull request closed without merging**
