### PR TITLE
gdb: overload DriverPgsql.ConvertDataForRecord to handle array structure

### LINKED ISSUE #1531: 往pg写入数组类型的数据会报错
### 1. What version of `Go` and system type/arch are you using?

go version go1.17.5 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf/v2 v2.0.0-beta

### 3. Can this issue be re-produced with the latest release?

YES

### 4. What did you do?

// 注：这里没法提供外网可访问的数据库地址
	sql := ` CREATE TABLE test_table ("code" varchar NOT NULL,"path" varchar[]); 
`
	db.Exec(sql)
	var data = g.Map{
		"code": "test",
		"path": []string{"c700a87b-e4d8-4aa1-aa18-38ebe107d0ae", "330cba76-8a69-4321-b783-199c53df64ae"},
	}
	db.Model("tablename").Data(data).Insert(data)

### 5. What did you expect to see?

希望可以支持数组类型的字段值写入pg数据库表中

### PR DESCRIPTION
**Pull request by mmyj**
### What problem does this PR solve?

Issue Number: close #1531

Problem Summary:

The `DriverPgsql` using base-class's `ConvertDataForRecord` function to convert slice

### What is changed and how it works?

Add a `DriverPgsql.ConvertDataForRecord` to handle array type, and the other type still invoke `Core.ConvertDataForRecord`

### CODE REVIEW

**Comment by mmyj** [comment]
PTAL @gqcn

**Comment by gqcn** [comment]
@mmyj Thanks for your PR, but it is duplicated with https://github.com/gogf/gf/pull/1535

**Comment by mmyj** [comment]
> @mmyj Thanks for your PR, but it is duplicated with #1535

@gqcn, It looks that the problem is still not fixed.

Following is my test case
```go
package main

import (
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gctx"
	_ "github.com/lib/pq"
)

func main() {
	var dbConfig = gdb.ConfigNode{
		Host:  "127.0.0.1",
		Port:  "5432",
		User:  "root",
		Pass:  "12345678",
		Name:  "test",
		Type:  "pgsql",
		Debug: true,
	}

	gdb.SetConfigGroup("MY_TEST", gdb.ConfigGroup{dbConfig})
	db, _ := gdb.New("MY_TEST")
	sql := `DROP TABLE IF EXISTS test_table;`
	db.Exec(gctx.New(), sql)
	sql = `CREATE TABLE test_table ("code" varchar NOT NULL,"path" varchar[]);`
	db.Exec(gctx.New(), sql)
	var data = g.Map{
		"code": "test",
		"path": []string{"c700a87b-e4d8-4aa1-aa18-38ebe107d0ae", "330cba76-8a69-4321-b783-199c53df64ae"},
	}
	db.Model("test_table").Data(data).Insert(data)
}
```

following is the output
```
2022-01-05 00:15:41.627 [ERRO] [  3 ms] [MY_TEST] [rows:0  ] INSERT INTO "test_table"("code","path") VALUES('test','["c700a87b-e4d8-4aa1-aa18-38ebe107d0ae","330cba76-8a69-4321-b783-199c53df64ae"]') 
Error: pq: malformed array literal: "["c700a87b-e4d8-4aa1-aa18-38ebe107d0ae","330cba76-8a69-4321-b783-199c53df64ae"]" 
Stack:
1.  github.com/gogf/gf/v2/database/gdb.(*Core).writeSqlToLogger
    /Users/mayj/sdk/gopath/src/github.com/mmyj/gf/database/gdb/gdb_core.go:652
2.  github.com/gogf/gf/v2/database/gdb.(*Core).DoCommit
    /Users/mayj/sdk/gopath/src/github.com/mmyj/gf/database/gdb/gdb_core_underlying.go:238
3.  github.com/gogf/gf/v2/database/gdb.(*Core).DoExec
    /Users/mayj/sdk/gopath/src/github.com/mmyj/gf/database/gdb/gdb_core_underlying.go:109
4.  github.com/gogf/gf/v2/database/gdb.(*Core).DoInsert
    /Users/mayj/sdk/gopath/src/github.com/mmyj/gf/database/gdb/gdb_core.go:441
5.  github.com/gogf/gf/v2/database/gdb.(*DriverPgsql).DoInsert
    /Users/mayj/sdk/gopath/src/github.com/mmyj/gf/database/gdb/gdb_driver_pgsql.go:205
6.  github.com/gogf/gf/v2/database/gdb.(*Model).doInsertWithOption
    /Users/mayj/sdk/gopath/src/github.com/mmyj/gf/database/gdb/gdb_model_insert.go:313
7.  github.com/gogf/gf/v2/database/gdb.(*Model).Insert
    /Users/mayj/sdk/gopath/src/github.com/mmyj/gf/database/gdb/gdb_model_insert.go:170
8.  github.com/gogf/gf/v2/database/gdb.(*Model).Insert
    /Users/mayj/sdk/gopath/src/github.com/mmyj/gf/database/gdb/gdb_model_insert.go:168
9.  main.main
    /Users/mayj/sdk/gopath/src/github.com/mmyj/mmyj-golab/20220101-gf/main.go:31
```

**Comment by starccck** [comment]
you can use method in [github.com/lib/pq.](https://github.com/lib/pq/blob/master/array.go) to get array type with existed solution

**Pull request closed without merging**
